version: '3.0'
services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - 127.0.0.1:4000:4000
    working_dir: /src/main
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: DB_HOST
      MYSQL_USER: DB_USERNAME
      MYSQL_PASSWORD: DB_PASSWORD
      MYSQL_DB: DB_DATABASE

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: